# DeluxeMenus 1.14.1-DEV-184 main configuration file
#
# A full wiki on how to use this plugin can be found at:
# https://wiki.helpch.at/clips-plugins/deluxemenus

debug: HIGHEST
check_updates: true
papi_chat: true
gui_menus:
  biomewarps_menu:
    file: biomewarps.yml
  guides_menu:
    file: guides.yml
  xur_shop_1:
    file: XurShopTable_1.yml
  xur_shop_test:
    file: xurshoptesting.yml
